# -*- coding: utf-8 -*-
"""project_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nH_v_TQdpA6bq6EszPdw2G21W5ao80C
"""



# Define your initial checklist
checklist = [
    "Wake up",
    "Make your bed",
    "Brush your teeth",
    "Eat breakfast",
    "Get dressed",
    "Check emails",
    "Start working on your project"
]

completed_tasks = []
incomplete_tasks = []

# Iterate through the checklist and ask the user for completion status
for task in checklist:
    status = input(f"Did you complete '{task}'? (yes/no): ")
    if status.lower() == "yes":
        completed_tasks.append(task)
    else:
        incomplete_tasks.append(task)

# Print the completed and incomplete tasks
print("\nCompleted Tasks:")
for task in completed_tasks:
    print(task)

print("\nIncomplete Tasks:")
for task in incomplete_tasks:
    print(task)